# Generated by Django 5.2.9 on 2025-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=1, upload_to='pic_file'),
            preserve_default=False,
        ),
    ]
